services:
  metube:
    image: ghcr.io/alexta69/metube:2025-05-01
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ${EXTERNAL_MEMORY}/data/audiobooks:/downloads
