services:
  app:
    image: 'jc21/nginx-proxy-manager:2'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ${PROJECT_ROOT}/data/nginx/data:/data
      - ${PROJECT_ROOT}/data/nginx/letsencrypt:/etc/letsencrypt
