---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${PROJECT_ROOT}/data/kavita/config:/config
      - ${EXTERNAL_MEMORY}/data/books:/data #optional
    ports:
      - 5000:5000
    restart: unless-stopped

