services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.15
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${PROJECT_ROOT}/data/sonarr:/config
      - ${EXTERNAL_MEMORY}/data/tvshows:/tv 
      - ${EXTERNAL_MEMORY}/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
