services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.26.2
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${PROJECT_ROOT}/data/radarr:/config
      - ${EXTERNAL_MEMORY}/data/movies:/movies 
      - ${EXTERNAL_MEMORY}/data/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
