services:
    jellyseerr:
       image: fallenbagel/jellyseerr:2.7.0
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe
       ports:
            - 5055:5055
       volumes:
            - ${PROJECT_ROOT}/data/jellyseer:/app/config
       restart: unless-stopped
